#!/bin/bash

for i in "$@"
do
case $i in
    -p=*|--port=*)
    PORT="${i#*=}"

    ;;
esac
done
gnome-terminal -x sh -c "rdmd simulator/server/sim_server.d --port=$PORT"
clear
echo $PORT
gnome-terminal -x sh -c "go run main.go -sim=true -sim_port=$PORT"
